Ext.create('Ext.Component', {
	renderTo: 'activity-feed'
	,data: ActivityData
	,tpl: [
		'<tpl for="workdays">'
			,'<section class="workday">'
				,'<header class="workday-header">'
				
					// !title
					,'<h2 class="workday-title"><time datetime><strong>{fuzzyName}</strong><span class="muted">, {date:date("j M Y")}</span></time></h2>'
					
					// !grouping options
					,'<form class="workday-grouping-options">'
						,'<label class="grouping-option"><input type="radio" name="grouping" checked><img alt="By User" title="By User" width=24 height=24 src="http://placehold.it/48/48"></label>'
						,'<label class="grouping-option"><input type="radio" name="grouping"><img alt="By Time" title="By Time" width=24 height=24 src="http://placehold.it/48/48"></label>'
						,'<label class="grouping-option"><input type="radio" name="grouping"><img alt="By File" title="By File" width=24 height=24 src="http://placehold.it/48/48"></label>'
					,'</form>'
					
					// !stat totals
					,'<div class="workday-change-summary">'
						,'<tpl for="statTotals">'
							,'<span class="{desc} count">'
								,'<strong class="numeral">{count}</strong>'
								,'&nbsp;'
								,'<tpl if="count==1">{singular}<tpl else>{plural}</tpl>'
							,'</span>'
						,'</tpl>'
					,'</div>'
					
					// !active users
					,'<ul class="workday-users">'
						,'<tpl for="activeUsers">'
							,'<li class="workday-user">'
								,'<a href="/people/{handle}" class="user-link">'
									,'<img class="user-avatar" alt="{fullName}" title="{fullName}" width=32 height=32 src="{avatarUrl}">'
								,'</a>'
							,'</li>'
						,'</tpl>'
					,'</ul>'

				,'</header>'
				
				// !activity groups
				,'<ul class="activity-groups">'
					,'<tpl for="activityGroups">'
						,'<li class="activity-group">'

							,'<header class="group-header">'
								,'<h3 class="group-title">'
									,'<tpl if="groupImg"><a href="{groupLink}" target=_blank><img class="group-image" alt="" width=32 height=32 src="{groupImg}"></a></tpl>'
									,'<span class="group-name">{groupName}</span>'
								,'</h3>'
								
								,'<div class="group-change-summary">'
									,'<tpl for="statTotals">'
										,'<span class="{desc} count">'
											,'<strong class="numeral">{count}</strong>'
											,'&nbsp;'
											,'<tpl if="count==1">{singular}<tpl else>{plural}</tpl>'
										,'</span>'
									,'</tpl>'
								,'</div>'
							,'</header>'
							
							// !log items
							,'<ul class="log-items">'
								,'<tpl for="logItems">'
									,'<li class="log-item">'

										,'<span class="log-item-verb {verb}">{verb}</span>'

										,'<tpl for="file">'
											,'<span class="file-path">'
												,'<span class="file-location">{location}</span>'
												,'<a href="/develop#{location}{name}" class="file-name">{name}</a>'
											,'</span>'

											,'<div class="log-item-actions">'
												,'<tpl if="previousRev"><a href="/develop#!diff?before={location}{name}@{previousRev}" class="log-item-action">compare</a></tpl>'
												// TODO: detect if "preview" is available and offer it
											,'</div>'
										,'</tpl>'

										,'<div class="log-item-info">'
											,'<tpl for="stats">'
												,'<tpl if="changeCount"><span class="change-count count"><strong class="numeral">{changeCount}</strong> times</span></tpl>'
												,'<time>{startTime:date("g:i a")}<tpl if="endTime">&nbsp;&ndash;&nbsp;{endTime:date("g:i a")}</tpl></time>' // TODO: smarter time range display
												,'<tpl if="hourCount"><span class="hour-count count"><strong class="numeral">{hourCount}</strong>h</span></tpl>'
											,'</tpl>'
										,'</div>'

									,'</li>' // log-item
								,'</tpl>'
							,'</ul>'
	
						,'</li>' // activity-group
					,'</tpl>'
				,'</ul>'
				
				
/*
				,'<ul class="activity-groups">'
					,'<li class="activity-group">'
						,'<header class="group-header">'
							,'<h3 class="group-title">'
								,'<img class="user-avatar" alt="Name Here" title="Name Here" width=32 height=32 src="http://placekitten.com/64/64">'
								
								,'<span class="user-name">Jon Sample</span>'
							,'</h3>'
							
							,'<div class="group-change-summary">'
								,'<span class="file-count count"><strong class="numeral">2</strong> files</span>'
								,'<span class="hour-count count"><strong class="numeral">1.8</strong> hours</span>'
							,'</div>'
						,'</header>',	
		
						,'<ul class="log-items">'
							,'<li class="log-item">'
								,'<span class="log-item-verb edited">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">EditorPanel.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">6</strong> times</span>'
									,'<time datetime>9:34&nbsp;&ndash;&nbsp;9:45&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">1</strong>h</span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb edited">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">Toolbar.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">5</strong> times</span>'
									,'<time datetime>9:37&nbsp;&ndash;&nbsp;9:43&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">.8</strong>h</span>'
								,'</div>'
							,'</li>'
						,'</ul>'
					,'</li>'
		
					,'<li class="activity-group">'
						,'<header class="group-header">'
							,'<h3 class="group-title">'
								,'<img class="user-avatar" alt="Name Here" title="Name Here" width=32 height=32 src="http://monkeyholder.com/64/64">'
								
								,'<span class="user-name">Ryon Coleman</span>'
							,'</h3>'
							
							,'<div class="group-change-summary">'
								,'<span class="file-count count"><strong class="numeral">3</strong> files</span>'
								,'<span class="hour-count count"><strong class="numeral">2.9</strong> hours</span>'
							,'</div>'
						,'</header>'
		
						,'<ul class="log-items">'
							,'<li class="log-item">'
								,'<span class="log-item-verb deleted">deleted</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">AppHeader.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"></span>'
									,'<time datetime>9:17&nbsp;pm</time>'
									,'<span class="hour-count count"></span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">created &amp; edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">Toolbar.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">5</strong> times</span>'
									,'<time datetime>9:37&nbsp;&ndash;&nbsp;9:43&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">.8</strong>h</span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/CMS/</span><a href="#" class="file-name">ContentEditor.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">14</strong> times</span>'
									,'<time datetime>6:20&nbsp;&ndash;&nbsp;8:58&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">2.6</strong>h</span>'
								,'</div>'
							,'</li>'
						,'</ul>'
					,'</li>'
		
					,'<li class="activity-group collapsed">'
						,'<header class="group-header">'
							,'<h3 class="group-title">'
								,'<img class="user-avatar" alt="Name Here" title="Name Here" width=32 height=32 src="http://placebear.com/64/64">'
								
								,'<span class="user-name">Chris Alfano</span>'
							,'</h3>'
							
							,'<div class="group-change-summary">'
								,'<span class="file-count count"><strong class="numeral">3</strong> files</span>'
								,'<span class="hour-count count"><strong class="numeral">2.9</strong> hours</span>'
							,'</div>'
						,'</header>'
						
						,'<ul class="log-items">'
							,'<li class="log-item">'
								,'<span class="log-item-verb deleted">deleted</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">AppHeader.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"></span>'
									,'<time datetime>9:17&nbsp;pm</time>'
									,'<span class="hour-count count"></span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">created &amp; edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">Toolbar.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">5</strong> times</span>'
									,'<time datetime>9:37&nbsp;&ndash;&nbsp;9:43&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">.8</strong>h</span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/CMS/</span><a href="#" class="file-name">ContentEditor.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">14</strong> times</span>'
									,'<time datetime>6:20&nbsp;&ndash;&nbsp;8:58&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">2.6</strong>h</span>'
								,'</div>'
							,'</li>'
						,'</ul>'
					,'</li>'
		
					,'<li class="activity-group collapsed">'
						,'<header class="group-header">'
							,'<h3 class="group-title">'
								,'<img class="user-avatar" alt="Name Here" title="Name Here" width=32 height=32 src="http://fillmurray.com/64/64">'
								
								,'<span class="user-name">Anthony Harley</span>'
							,'</h3>'
							
							,'<div class="group-change-summary">'
								,'<span class="file-count count"><strong class="numeral">3</strong> files</span>'
								,'<span class="hour-count count"><strong class="numeral">2.9</strong> hours</span>'
							,'</div>'
						,'</header>'
						
						,'<ul class="log-items">'
							,'<li class="log-item">'
								,'<span class="log-item-verb deleted">deleted</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">AppHeader.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"></span>'
									,'<time datetime>9:17&nbsp;pm</time>'
									,'<span class="hour-count count"></span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">created &amp; edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">Toolbar.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">5</strong> times</span>'
									,'<time datetime>9:37&nbsp;&ndash;&nbsp;9:43&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">.8</strong>h</span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/CMS/</span><a href="#" class="file-name">ContentEditor.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">14</strong> times</span>'
									,'<time datetime>6:20&nbsp;&ndash;&nbsp;8:58&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">2.6</strong>h</span>'
								,'</div>'
							,'</li>'
						,'</ul>'
					,'</li>'
		
					,'<li class="activity-group collapsed">'
						,'<header class="group-header">'
							,'<h3 class="group-title">'
								,'<img class="user-avatar" alt="Name Here" title="Name Here" width=32 height=32 src="http://placeowl.com/64/64">'
								
								,'<span class="user-name">Ryon Coleman</span>'
							,'</h3>'
							
							,'<div class="group-change-summary">'
								,'<span class="file-count count"><strong class="numeral">3</strong> files</span>'
								,'<span class="hour-count count"><strong class="numeral">2.9</strong> hours</span>'
							,'</div>'
						,'</header>'
		
						,'<ul class="log-items">'
							,'<li class="log-item">'
								,'<span class="log-item-verb deleted">deleted</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">AppHeader.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"></span>'
									,'<time datetime>9:17&nbsp;pm</time>'
									,'<span class="hour-count count"></span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb created">created &amp; edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/view/</span><a href="#" class="file-name">Toolbar.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">5</strong> times</span>'
									,'<time datetime>9:37&nbsp;&ndash;&nbsp;9:43&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">.8</strong>h</span>'
								,'</div>'
							,'</li>'
		
							,'<li class="log-item">'
								,'<span class="log-item-verb edited">edited</span>'
								,'<span class="file-path"><span class="file-location">/sencha-workspace/SampleApp/app/CMS/</span><a href="#" class="file-name">ContentEditor.js</a></span>'
								,'<div class="log-item-actions">'
									,'<a class="log-item-action" href="#">compare</a>'
								,'</div>'
								,'<div class="log-item-info">'
									,'<span class="change-count count"><strong class="numeral">14</strong> times</span>'
									,'<time datetime>6:20&nbsp;&ndash;&nbsp;8:58&nbsp;pm</time>'
									,'<span class="hour-count count"><strong class="numeral">2.6</strong>h</span>'
								,'</div>'
							,'</li>'
						,'</ul>'
					,'</li>'
				,'</ul>'
*/
			,'</section>'
		,'</tpl>'
	]
});