
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "EmergenceEditor2.Application": "app/Application.js",
  " Ext.Msg": "../ext/src/window/MessageBox.js",
  "Ext": "../ext/src",
  "EmergenceEditor2": "app",
  "Ext.rtl.EventObjectImpl": "../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "EmergenceEditor2.controller.Main": [],
  "EmergenceEditor2.Application": [],
  "EmergenceEditor2.view.Main": [],
  "EmergenceEditor2.view.Viewport": []
});
Ext.ClassManager.addNameAliasMappings({
  "EmergenceEditor2.controller.Main": [],
  "EmergenceEditor2.Application": [],
  "EmergenceEditor2.view.Main": [
    "widget.app-main"
  ],
  "EmergenceEditor2.view.Viewport": []
});
